baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

theme = 'hugo-scroll'

[params]
title = 'Datathon'